# TASK 3

# Question 3.1

studentscores = ([[80,70,90],

                  [60,85,75],

                   [95,88,92],
                   
                   [70,60,65] ])

# Question 3.2
                total score for student 1 = 80 + 70 + 90
                                          = 240
                total score for student 2 = 60 + 85 + 75
                                          = 220
                total score for student 3 = 95 + 88 + 92
                                          = 275
                total score for student 4 = 70 + 60 + 65
                                          = 195


# Question 3.3

**Applying weights (scalar multiplication)**

weight = (2 ,1,1)

weighted score = weight * (corresponding column studentscore)
               2*([[80],[60],[95],[70])
               = ([[160],[120],[190],[140]])

               since the remaining columns are multiplied by 1 the value doesnt change 
               Therefore the resulting weighted score is given below

               = ([[160,70,90],

                  [120,85,75],

                   [190,88,92],
                   
                   [140,60,65] ])


# Question 3.4 

   **Average score per subject**

     colum_mathemean =   (80 + 60 + 95 + 70)/4
                     =  76.25

      columneng_mean = (70 + 85 + 88 + 60)/4
                     =  75.75

      column_sci_mean = (90 + 75 + 92 + 65)/4
                      =  80.5


# Question 3.5 

for matrix multiplicatin, number of column in the first matrix must be equal to the number of row in the second matrix


final score = ([[80,70,90],[60,85,75],[95,88,92],[70,60,65] ])   * ([[2],[1],[1]])

([
   [80*2 + 70*1 + 90*1],

   [60*2 + 85*1 + 75*1],

   [95*2 + 88*1 + 92*1],

   [70*2 + 60*1 + 65*1]
])

final grade  = ([
                     [300]

                     [280]

                     [370]

                     [265]
])



# Questiob 3.6 

comparing student 1 and 3 

we have  300 - 370 = -70 

which means student 1 performed 70 weight less than student 2 

In [4]:
import numpy as np

In [5]:
# Question 3.1
studentscores = np.array([[80,70,90],[60,85,75], [95,88,92],[70,60,65] ])
 

# Question 3.2
sumstudent1 = studentscores[0].sum()
sumstudent2 = studentscores[1].sum()
sumstudent3 = studentscores[2].sum()
sumstudent4 = studentscores[3].sum()

print("The sum of student1 scores is: ",sumstudent1,"\n")
print("The sum of student2 scores is: ",sumstudent2,"\n")
print("The sum of student3 scores is: ",sumstudent3,"\n")
print("The sum of student4 scores is: ",sumstudent4,"\n")

The sum of student1 scores is:  240 

The sum of student2 scores is:  220 

The sum of student3 scores is:  275 

The sum of student4 scores is:  195 



In [6]:
# Question 3.3

weight = (2 ,1,1)
# scalar multiplication of vectors 
weightedscore = weight * studentscores
weightedscore

array([[160,  70,  90],
       [120,  85,  75],
       [190,  88,  92],
       [140,  60,  65]])

In [7]:
# Question 3.4

averagemath = studentscores[:,0].mean()
averageenglish = studentscores[:,1].mean()
averagesci = studentscores[:,2].mean()

print("The Average score for mathematics is : ",averagemath,"\n")
print("The Average score for English is : ",averageenglish,"\n")
print("The Average score for science is : ",averagesci,"\n")

The Average score for mathematics is :  76.25 

The Average score for English is :  75.75 

The Average score for science is :  80.5 



In [8]:
#Question 3.5
weightmatrix = np.array([[2],[1],[1]])
finalscore = np.dot(studentscores,weightmatrix)
print("The final scores are:\n ",finalscore)

The final scores are:
  [[320]
 [280]
 [370]
 [265]]


In [9]:
#Question 3.6 
# comparing student one and three

compare = np.array_equal(finalscore[0],finalscore[2])
print("Did student1 and student two performed differently? ", compare)

Did student1 and student two performed differently?  False


# Question 5

In [11]:
studentscoresnew = np.array([[80,70,90,60],[60,85,75,78], [95,88,92,88],[70,60,65,80] ,[100,88,96,99]])

In [23]:
# Question 3.2
sumstudentnew = studentscoresnew[0].sum()
sumstudentnew2 = studentscoresnew[1].sum()
sumstudentnew3 = studentscoresnew[2].sum()
sumstudentnew4 = studentscoresnew[3].sum()
sumstudentnew5 = studentscoresnew[4].sum()

print("The sum of student1 scores is: ",sumstudentnew,"\n")
print("The sum of student2 scores is: ",sumstudentnew2,"\n")
print("The sum of student3 scores is: ",sumstudentnew3,"\n")
print("The sum of student4 scores is: ",sumstudentnew4,"\n")
print("The sum of student5 scores is: ",sumstudentnew5,"\n")

The sum of student1 scores is:  300 

The sum of student2 scores is:  298 

The sum of student3 scores is:  363 

The sum of student4 scores is:  275 

The sum of student5 scores is:  383 



In [26]:
averagenewmath = studentscoresnew[:,0].mean()
averagenewenglish = studentscoresnew[:,1].mean()
averagenewsci = studentscoresnew[:,2].mean()
averagenewtech = studentscoresnew[:,3].mean()


print("The Average score for mathematics is : ",averagenewmath,"\n")
print("The Average score for English is : ",averagenewenglish,"\n")
print("The Average score for science is : ",averagenewsci,"\n")
print("The Average score for technical drawing is : ",averagenewtech,"\n")


The Average score for mathematics is :  81.0 

The Average score for English is :  78.2 

The Average score for science is :  83.6 

The Average score for technical drawing is :  81.0 



In [28]:
weightnew = (3 ,1,1,1)
# scalar multiplication of vectors 
weightedscorenew = weightnew * studentscoresnew
weightedscorenew

array([[240,  70,  90,  60],
       [180,  85,  75,  78],
       [285,  88,  92,  88],
       [210,  60,  65,  80],
       [300,  88,  96,  99]])

In [30]:
weightmatrixnew = np.array([[40/100],[20/100],[20/100],[20/100]])
finalscorenew = np.dot(studentscoresnew,weightmatrixnew)
print("The final scores are:\n ",finalscorenew)

The final scores are:
  [[76. ]
 [71.6]
 [91.6]
 [69. ]
 [96.6]]


In [ ]:
#comparing student 3 and student 4 scores 
comparednew = np.subtract(finalscorenew[2],finalscorenew[3])
#
print("compared students difference: ",comparednew)

compared students difference:  [22.6]
