In [1]:
import numpy as np
import random

#check Numpy version
print(f"Numpy Version: {np.__version__}" )

#display settings for cleaner output 
np.set_printoptions(precision=3, suppress=True)

Numpy Version: 2.2.0


QUESTION 1

**Create a 6x6 NumPy array with random integers between 1 and 50. Display the array.**

In [5]:
arr= np.random.randint(50,size=(6,6))
print(arr)

[[48 35 12 42 10  6]
 [ 9 43  6 10 38 44]
 [ 9 17 11 44 40  7]
 [12 44 17 19 41 45]
 [13 14 39 33 40 14]
 [45 33 42  2  0  6]]


Question 2

In [ ]:
print("first 2 rows: ", arr[:2])
print("last three colums: ", arr[:,3:])
print ("even numbers: ", arr[arr % 2 == 0])

first 2 rows:  [[48 35 12 42 10  6]
 [ 9 43  6 10 38 44]]
last three colums:  [[42 10  6]
 [10 38 44]
 [44 40  7]
 [19 41 45]
 [33 40 14]
 [ 2  0  6]]


Question 3

In [13]:
reshaped_array3d = arr.reshape(3,2,6)
print("The redhaped array is", reshaped_array3d)

flatreshaped= reshaped_array3d.flatten()
print("the flattened reshaped array", flatreshaped)

The redhaped array is [[[48 35 12 42 10  6]
  [ 9 43  6 10 38 44]]

 [[ 9 17 11 44 40  7]
  [12 44 17 19 41 45]]

 [[13 14 39 33 40 14]
  [45 33 42  2  0  6]]]
the flattened reshaped array [48 35 12 42 10  6  9 43  6 10 38 44  9 17 11 44 40  7 12 44 17 19 41 45
 13 14 39 33 40 14 45 33 42  2  0  6]


Question 4

In [2]:
identity_matrix = np.eye(4)
print(identity_matrix)
diagonal_array = np.arange(10,40,10)
diagonal_matrix  = np.array(diagonal_array)
np.fill_diagonal(identity_matrix,diagonal_array)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 10.]]


Question 5

In [8]:
arr1 = np.random.randint(1,10,size=(3,4))
arr2 = np.random.randint(1,10,size=(4,3))
product = np.dot(arr1,arr2)

print("The product of the two matrices is :\n",product)

The product of the two matrices is :
 [[116 182 118]
 [134 189 153]
 [107 136 133]]


Question 6

In [11]:
#a function that takes a 2d array as input and squares the even number and also changes odd numbers to -1
def TwoDarray(twoDarray):
    newarray= np.where(twoDarray%2 ==0,twoDarray**2,-1)
    return newarray
#ask the user for how many rows the matrix is 
x= int(input("how many rows should it be"))
y= int(input("how many column should it be"))
numberOfelements= x*y
array =[]
for i in range(1,numberOfelements+1):
    thenumber= int(input("the numbers"))
    array.append(thenumber)

readyarray=np.array(array).reshape(x,y)
print("array before converting:\n",readyarray)
print("New array:\n", TwoDarray(readyarray))

array before converting:
 [[1 2 4]
 [5 7 8]
 [9 1 3]]
New array:
 [[-1  4 16]
 [-1 -1 64]
 [-1 -1 -1]]
