# TASK 3

In [1]:
import numpy as np

A = [[2,-1],[0,3]]   

B=[[1,4],[-2,5]] 

c= 2 , d = 3

# Question 1
compute the following. (cA), (dB), and (c+d)A


cA = 2.([[2,-1],[0,3]])

    = [[ 4, -2],
       [ 0,  6]]

dB = 3.([[1,4],[-2,5]])

   =  [[ 3, 12],
       [-6, 15]]

(c+d)A = (2+3)([[2,-1],[0,3]])

        = (5)([[2,-1],[0,3]])

# QUESTION 2

ASSOCIATIVITY of scalar multiplication

cA = Ac 

2.([[2,-1],[0,3]])  =  ([[2,-1],[0,3]]). 2

[[4,-2],[0,6]]    = [[4,-2],[0,6]]


dB = Bd

3.([[1,4],[-2,5]])  =  ([[1,4],[-2,5]]).3

[[3,12],[-6,15]]  =  [[3,12],[-6,15]]

distributive property over scalar addition

(c+d)A = cA + dA

(5)([[2,-1],[0,3]]) = 2.([[2,-1],[0,3]])  + 3.([[2,-1],[0,3]])

[[10,-5],[0,15]] =   [[4,-2],[0,6]]  +  [[6,-3],[0,9]] 

[[10,-5],[0,15]]  =  [[10,-5],[0,15]]





# QUESTION 3 


transpose of A : [[2,-1],[0,3]]    = [[2,0],[-1,3]]


transpose of B : [[1,4],[-2,5]]   =  [[1,-2],[4,5]]

# QUESTION 4

det(A)= (2x3)-(0 x-1)
    
    = 6  (since 6 is non zero it means A has a determinant and it is invertible)

Inverse of A = [[3,1],[0,2]]/6

            = [[1/2,1/6],[0,1/3]]

det(B)= (1x5)-(-2 x 4)
    
    = 5 - (-8) = 13  (since 13 is non zero it means B has a determinant and it is invertible)

Inverse of B = [[5,-4],[2,1]] /13

             = [[5/13,-4/13],[2/13,1/13]]

In [3]:
matA = np.array([[2,-1],[0,3]])
matB= np.array([[1,4],[-2,5]])
c =2
d=3



In [4]:
np.dot(c,matA)

array([[ 4, -2],
       [ 0,  6]])

In [5]:
np.dot(matA,c)

array([[ 4, -2],
       [ 0,  6]])

In [6]:
np.dot(d,matB)

array([[ 3, 12],
       [-6, 15]])

In [7]:
np.dot(matB,d)

array([[ 3, 12],
       [-6, 15]])

In [8]:
np.dot((c+d),matA)

array([[10, -5],
       [ 0, 15]])

In [9]:
np.dot(c,matA) + np.dot(d,matA)

array([[10, -5],
       [ 0, 15]])

In [12]:
#geting determinant of A 
determinantA= np.linalg.det(matA)
print("determinant of A is: ",determinantA )

determinant of A is:  6.0


In [13]:
#geting determinant of B 
determinantB= np.linalg.det(matB)
print("determinant of B is: ",determinantB )

determinant of B is:  13.0


In [14]:
np.linalg.inv(matA)

array([[0.5       , 0.16666667],
       [0.        , 0.33333333]])

In [15]:
np.linalg.inv(matB)

array([[ 0.38461538, -0.30769231],
       [ 0.15384615,  0.07692308]])