# TASK 2


A = [[2 -1 3], [0 4 1]]

B = [[1 2], [-2 0], [5 3]]

Question 1. Identify the number of rows and columns in each matrix
Question 2. Determine whether the matrices can be multiplied. If so, specify whether its (AB), (BA) or both.
Question3. If the multiplication is defined, compute the resulting matrix

Qestion A


Matric A has:  
Rows = 2
Columns = 3

Matrix B has:
Rows = 3
Columns = 2




Question B


The matric A can be multiplied by Matric B because number of column in A is equal to the number of rows in B

The matric B can also be multiplied by Matric A because number of column in B is equal to the number of rows in A


In [2]:
import numpy as np
matA = np.array([[2,-1,3],[0,4,1]])
matB = np.array([[1,2],[-2,0],[5,-3]])

In [4]:
#matrix multiplication AB
multiAB = np.dot(matA,matB)
print("The matrix multiplication of matric A and B is \n",multiAB)

The matrix multiplication of matric A and B is 
 [[19 -5]
 [-3 -3]]


In [5]:
#matrix multiplication AB
multiBA = np.dot(matB,matA)
print("The matrix multiplication of matric A and B is \n",multiBA)

The matrix multiplication of matric A and B is 
 [[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
