# Mathematics Task

Question A

In [2]:
import numpy as np

In [3]:
matA = np.array([[2,-1],[0,3]])
matB= np.array([[1,4],[-2,5]])
c =2
d=3


In [4]:
left =np.dot(c,matA)
right = np.dot(matA,c)

In [5]:
print("The output of cA is:\n",left)

The output of cA is:
 [[ 4 -2]
 [ 0  6]]


In [6]:
left2 =np.dot(d,matB)
right2 =np.dot(matB,d)

In [7]:
print("The output of dB is:\n",left2)

The output of dB is:
 [[ 3 12]
 [-6 15]]


In [8]:
left3 = np.dot((c+d),matA)
right3 = np.dot(c,matA) + np.dot(d,matA)

In [9]:
print("The output of (c+d)A is:\n",left3)

The output of (c+d)A is:
 [[10 -5]
 [ 0 15]]


Associativity of scalar multiplication

In [10]:
associativity = np.array_equal(left,right)
print("The statement cA obeys the associativity property of scalar multiplication is: ", associativity)

The statement cA obeys the associativity property of scalar multiplication is:  True


In [11]:
associativity2 = np.array_equal(left2,right2)
print("The statement dB obeys the associativity property of scalar multiplication is: ", associativity)

The statement dB obeys the associativity property of scalar multiplication is:  True


In [12]:
distributive = np.array_equal(left3,right3)
print("The statement (c+d)A obeys the distributive property over scalar multiplication is: ", associativity)

The statement (c+d)A obeys the distributive property over scalar multiplication is:  True


In [13]:
#geting determinant of A 
determinantA= np.linalg.det(matA)
print("determinant of A is: ",determinantA )

determinant of A is:  6.0


In [14]:
#geting determinant of B 
determinantB= np.linalg.det(matB)
print("determinant of B is: ",determinantB )

determinant of B is:  13.0


In [15]:
matAinverse =np.linalg.inv(matA)
matBinverse= np.linalg.inv(matB)

In [16]:
print("the inverse of matrix A is : \n",matAinverse ,"\n")


print("the inverse of matrix B is : \n",matBinverse)

the inverse of matrix A is : 
 [[0.5        0.16666667]
 [0.         0.33333333]] 

the inverse of matrix B is : 
 [[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]
